//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityDataTools.Analyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddrBuildBundleDependencies {
            get {
                return ResourceManager.GetString("AddrBuildBundleDependencies", resourceCulture);
            }
        }
        
        internal static string AddrBuildBundleDependentBundles {
            get {
                return ResourceManager.GetString("AddrBuildBundleDependentBundles", resourceCulture);
            }
        }
        
        internal static string AddrBuildBundleExpandedDependencies {
            get {
                return ResourceManager.GetString("AddrBuildBundleExpandedDependencies", resourceCulture);
            }
        }
        
        internal static string AddrBuildBundleFiles {
            get {
                return ResourceManager.GetString("AddrBuildBundleFiles", resourceCulture);
            }
        }
        
        internal static string AddrBuildBundleRegularDependencies {
            get {
                return ResourceManager.GetString("AddrBuildBundleRegularDependencies", resourceCulture);
            }
        }
        
        internal static string AddrBuildBundles {
            get {
                return ResourceManager.GetString("AddrBuildBundles", resourceCulture);
            }
        }
        
        internal static string AddrBuildDataFromOtherAssetObjectReferences {
            get {
                return ResourceManager.GetString("AddrBuildDataFromOtherAssetObjectReferences", resourceCulture);
            }
        }
        
        internal static string AddrBuildDataFromOtherAssetObjects {
            get {
                return ResourceManager.GetString("AddrBuildDataFromOtherAssetObjects", resourceCulture);
            }
        }
        
        internal static string AddrBuildDataFromOtherAssetReferencingAssets {
            get {
                return ResourceManager.GetString("AddrBuildDataFromOtherAssetReferencingAssets", resourceCulture);
            }
        }
        
        internal static string AddrBuildDataFromOtherAssets {
            get {
                return ResourceManager.GetString("AddrBuildDataFromOtherAssets", resourceCulture);
            }
        }
        
        internal static string AddrBuildExplicitAssetExternallyReferencedAssets {
            get {
                return ResourceManager.GetString("AddrBuildExplicitAssetExternallyReferencedAssets", resourceCulture);
            }
        }
        
        internal static string AddrBuildExplicitAssetInternalReferencedExplicitAssets {
            get {
                return ResourceManager.GetString("AddrBuildExplicitAssetInternalReferencedExplicitAssets", resourceCulture);
            }
        }
        
        internal static string AddrBuildExplicitAssetInternalReferencedOtherAssets {
            get {
                return ResourceManager.GetString("AddrBuildExplicitAssetInternalReferencedOtherAssets", resourceCulture);
            }
        }
        
        internal static string AddrBuildExplicitAssetLabels {
            get {
                return ResourceManager.GetString("AddrBuildExplicitAssetLabels", resourceCulture);
            }
        }
        
        internal static string AddrBuildExplicitAssets {
            get {
                return ResourceManager.GetString("AddrBuildExplicitAssets", resourceCulture);
            }
        }
        
        internal static string AddrBuildFileAssets {
            get {
                return ResourceManager.GetString("AddrBuildFileAssets", resourceCulture);
            }
        }
        
        internal static string AddrBuildFileExternalReferences {
            get {
                return ResourceManager.GetString("AddrBuildFileExternalReferences", resourceCulture);
            }
        }
        
        internal static string AddrBuildFileOtherAssets {
            get {
                return ResourceManager.GetString("AddrBuildFileOtherAssets", resourceCulture);
            }
        }
        
        internal static string AddrBuildFiles {
            get {
                return ResourceManager.GetString("AddrBuildFiles", resourceCulture);
            }
        }
        
        internal static string AddrBuildFileSubFiles {
            get {
                return ResourceManager.GetString("AddrBuildFileSubFiles", resourceCulture);
            }
        }
        
        internal static string AddrBuildGroupBundles {
            get {
                return ResourceManager.GetString("AddrBuildGroupBundles", resourceCulture);
            }
        }
        
        internal static string AddrBuildGroups {
            get {
                return ResourceManager.GetString("AddrBuildGroups", resourceCulture);
            }
        }
        
        internal static string AddrBuildGroupSchemas {
            get {
                return ResourceManager.GetString("AddrBuildGroupSchemas", resourceCulture);
            }
        }
        
        internal static string AddrBuilds {
            get {
                return ResourceManager.GetString("AddrBuilds", resourceCulture);
            }
        }
        
        internal static string AddrBuildSchemaDataPairs {
            get {
                return ResourceManager.GetString("AddrBuildSchemaDataPairs", resourceCulture);
            }
        }
        
        internal static string AddrBuildSchemas {
            get {
                return ResourceManager.GetString("AddrBuildSchemas", resourceCulture);
            }
        }
        
        internal static string AddrBuildSubFiles {
            get {
                return ResourceManager.GetString("AddrBuildSubFiles", resourceCulture);
            }
        }
        
        internal static string AnimationClip {
            get {
                return ResourceManager.GetString("AnimationClip", resourceCulture);
            }
        }
        
        internal static string AssetBundle {
            get {
                return ResourceManager.GetString("AssetBundle", resourceCulture);
            }
        }
        
        internal static string AudioClip {
            get {
                return ResourceManager.GetString("AudioClip", resourceCulture);
            }
        }

        internal static string BuildReport {
            get {
                return ResourceManager.GetString("BuildReport", resourceCulture);
            }
        }

        internal static string ContentLayout {
            get {
                return ResourceManager.GetString("ContentLayout", resourceCulture);
            }
        }

        internal static string ContentLayoutArtifactReferences {
            get {
                return ResourceManager.GetString("ContentLayoutArtifactReferences", resourceCulture);
            }
        }

        internal static string ContentLayoutBinaryArtifacts {
            get {
                return ResourceManager.GetString("ContentLayoutBinaryArtifacts", resourceCulture);
            }
        }

        internal static string ContentLayoutIndexes {
            get {
                return ResourceManager.GetString("ContentLayoutIndexes", resourceCulture);
            }
        }

        internal static string ContentLayoutLoadableDependencies {
            get {
                return ResourceManager.GetString("ContentLayoutLoadableDependencies", resourceCulture);
            }
        }

        internal static string ContentLayoutLoadableObjects {
            get {
                return ResourceManager.GetString("ContentLayoutLoadableObjects", resourceCulture);
            }
        }

        internal static string ContentLayoutLoadableSceneDependencies {
            get {
                return ResourceManager.GetString("ContentLayoutLoadableSceneDependencies", resourceCulture);
            }
        }

        internal static string ContentLayoutLoadableScenes {
            get {
                return ResourceManager.GetString("ContentLayoutLoadableScenes", resourceCulture);
            }
        }

        internal static string ContentLayoutSerializedFileDependencies {
            get {
                return ResourceManager.GetString("ContentLayoutSerializedFileDependencies", resourceCulture);
            }
        }

        internal static string ContentLayoutSerializedFiles {
            get {
                return ResourceManager.GetString("ContentLayoutSerializedFiles", resourceCulture);
            }
        }

        internal static string ContentLayoutSourceAssets {
            get {
                return ResourceManager.GetString("ContentLayoutSourceAssets", resourceCulture);
            }
        }

        internal static string ContentLayoutViews {
            get {
                return ResourceManager.GetString("ContentLayoutViews", resourceCulture);
            }
        }

        internal static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        internal static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        internal static string Mesh {
            get {
                return ResourceManager.GetString("Mesh", resourceCulture);
            }
        }
        
        internal static string Shader {
            get {
                return ResourceManager.GetString("Shader", resourceCulture);
            }
        }
        
        internal static string Texture2D {
            get {
                return ResourceManager.GetString("Texture2D", resourceCulture);
            }
        }

        internal static string MonoScript {
            get {
                return ResourceManager.GetString("MonoScript", resourceCulture);
            }
        }

        internal static string PackedAssets {
            get {
                return ResourceManager.GetString("PackedAssets", resourceCulture);
            }
        }

        internal static string ContentSummary {
            get {
                return ResourceManager.GetString("ContentSummary", resourceCulture);
            }
        }
    }
}
