//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_bundle_dependencies
        ///(
        ///    bundle_id INTEGER,
        ///    build_id INTEGER,
        ///    dependency_rid INTEGER,
        ///    PRIMARY KEY (bundle_id, build_id, dependency_rid),
        ///    FOREIGN KEY (bundle_id, build_id) REFERENCES addr_build_bundles(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildBundleDependencies {
            get {
                return ResourceManager.GetString("AddrBuildBundleDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_bundle_dependent_bundles
        ///(
        ///    bundle_id INTEGER,
        ///    build_id INTEGER,
        ///    dependent_bundle_rid INTEGER,
        ///    PRIMARY KEY (bundle_id, build_id, dependent_bundle_rid),
        ///    FOREIGN KEY (bundle_id, build_id) REFERENCES addr_build_bundles(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildBundleDependentBundles {
            get {
                return ResourceManager.GetString("AddrBuildBundleDependentBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_bundle_expanded_dependencies
        ///(
        ///    bundle_id INTEGER,
        ///    build_id INTEGER,
        ///    dependency_rid INTEGER,
        ///    PRIMARY KEY (bundle_id, build_id, dependency_rid),
        ///    FOREIGN KEY (bundle_id, build_id) REFERENCES addr_build_bundles(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildBundleExpandedDependencies {
            get {
                return ResourceManager.GetString("AddrBuildBundleExpandedDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_bundle_files
        ///(
        ///    bundle_id INTEGER,
        ///    build_id INTEGER,
        ///    file_rid INTEGER,
        ///    PRIMARY KEY (bundle_id, build_id, file_rid),
        ///    FOREIGN KEY (bundle_id, build_id) REFERENCES addr_build_bundles(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildBundleFiles {
            get {
                return ResourceManager.GetString("AddrBuildBundleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_bundle_regular_dependencies
        ///(
        ///    bundle_id INTEGER,
        ///    build_id INTEGER,
        ///    dependency_rid INTEGER,
        ///    PRIMARY KEY (bundle_id, build_id, dependency_rid),
        ///    FOREIGN KEY (bundle_id, build_id) REFERENCES addr_build_bundles(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildBundleRegularDependencies {
            get {
                return ResourceManager.GetString("AddrBuildBundleRegularDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_bundles
        ///(
        ///    id INTEGER,
        ///    build_id INTEGER,
        ///    asset_count INTEGER,
        ///    build_status INTEGER,
        ///    crc INTEGER,
        ///    compression TEXT,
        ///    dependency_file_size INTEGER,
        ///    expanded_dependency_file_size INTEGER,
        ///    file_size INTEGER,
        ///    group_rid INTEGER,
        ///    hash TEXT,
        ///    internal_name TEXT,
        ///    load_path TEXT,
        ///    name TEXT,
        ///    provider TEXT,
        ///    result_type TEXT,
        ///    PRIMARY KEY (id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildBundles {
            get {
                return ResourceManager.GetString("AddrBuildBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_data_from_other_asset_object_references
        ///(
        ///    data_from_other_asset_id INTEGER,
        ///    build_id INTEGER,
        ///    local_identifier_in_file INTEGER,
        ///    asset_id INTEGER,
        ///    object_id INTEGER,
        ///    PRIMARY KEY (data_from_other_asset_id, build_id, local_identifier_in_file, asset_id, object_id),
        ///    FOREIGN KEY (data_from_other_asset_id, build_id, local_identifier_in_file) REFERENCES addr_build_data_from_other_asset_objects(data_from_other_asset_id, build_id, local_identifier_in_file)
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddrBuildDataFromOtherAssetObjectReferences {
            get {
                return ResourceManager.GetString("AddrBuildDataFromOtherAssetObjectReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_data_from_other_asset_objects
        ///(
        ///    data_from_other_asset_id INTEGER,
        ///    build_id INTEGER,
        ///    asset_type INTEGER,
        ///    component_name TEXT,
        ///    local_identifier_in_file INTEGER,
        ///    object_name TEXT,
        ///    serialized_size INTEGER,
        ///    streamed_size INTEGER,
        ///    PRIMARY KEY (data_from_other_asset_id, build_id, local_identifier_in_file),
        ///    FOREIGN KEY (data_from_other_asset_id, build_id) REFERENCES addr_build_data_from_other_assets(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildDataFromOtherAssetObjects {
            get {
                return ResourceManager.GetString("AddrBuildDataFromOtherAssetObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_data_from_other_asset_referencing_assets
        ///(
        ///    data_from_other_asset_id INTEGER,
        ///    build_id INTEGER,
        ///    referencing_asset_rid INTEGER,
        ///    PRIMARY KEY (data_from_other_asset_id, build_id, referencing_asset_rid),
        ///    FOREIGN KEY (data_from_other_asset_id, build_id) REFERENCES addr_build_data_from_other_assets(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildDataFromOtherAssetReferencingAssets {
            get {
                return ResourceManager.GetString("AddrBuildDataFromOtherAssetReferencingAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_data_from_other_assets
        ///(
        ///    id INTEGER,
        ///    build_id INTEGER,
        ///    asset_guid TEXT,
        ///    asset_path TEXT,
        ///    file INTEGER,
        ///    main_asset_type INTEGER,
        ///    object_count INTEGER,
        ///    serialized_size INTEGER,
        ///    streamed_size INTEGER,
        ///    PRIMARY KEY (id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildDataFromOtherAssets {
            get {
                return ResourceManager.GetString("AddrBuildDataFromOtherAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_explicit_asset_externally_referenced_assets
        ///(
        ///    explicit_asset_id INTEGER,
        ///    build_id INTEGER,
        ///    externally_referenced_asset_rid INTEGER,
        ///    PRIMARY KEY (explicit_asset_id, build_id, externally_referenced_asset_rid),
        ///    FOREIGN KEY (explicit_asset_id, build_id) REFERENCES addr_build_explicit_assets(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildExplicitAssetExternallyReferencedAssets {
            get {
                return ResourceManager.GetString("AddrBuildExplicitAssetExternallyReferencedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_explicit_asset_internal_referenced_explicit_assets
        ///(
        ///    explicit_asset_id INTEGER,
        ///    build_id INTEGER,
        ///    internal_referenced_explicit_asset_rid INTEGER,
        ///    PRIMARY KEY (explicit_asset_id, build_id, internal_referenced_explicit_asset_rid),
        ///    FOREIGN KEY (explicit_asset_id, build_id) REFERENCES addr_build_explicit_assets(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildExplicitAssetInternalReferencedExplicitAssets {
            get {
                return ResourceManager.GetString("AddrBuildExplicitAssetInternalReferencedExplicitAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_explicit_asset_internal_referenced_other_assets
        ///(
        ///    explicit_asset_id INTEGER,
        ///    build_id INTEGER,
        ///    internal_referenced_other_asset_rid INTEGER,
        ///    PRIMARY KEY (explicit_asset_id, build_id, internal_referenced_other_asset_rid),
        ///    FOREIGN KEY (explicit_asset_id, build_id) REFERENCES addr_build_explicit_assets(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildExplicitAssetInternalReferencedOtherAssets {
            get {
                return ResourceManager.GetString("AddrBuildExplicitAssetInternalReferencedOtherAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_explicit_asset_labels
        ///(
        ///    explicit_asset_id INTEGER,
        ///    build_id INTEGER,
        ///    label TEXT,
        ///    PRIMARY KEY (explicit_asset_id, build_id, label),
        ///    FOREIGN KEY (explicit_asset_id, build_id) REFERENCES addr_build_explicit_assets(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildExplicitAssetLabels {
            get {
                return ResourceManager.GetString("AddrBuildExplicitAssetLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_explicit_assets
        ///(
        ///    id INTEGER,
        ///    build_id INTEGER,
        ///    bundle INTEGER,
        ///    file INTEGER,
        ///    asset_hash TEXT,
        ///    asset_path TEXT,
        ///    addressable_name TEXT,
        ///    group_guid TEXT,
        ///    guid TEXT,
        ///    internal_id TEXT,
        ///    main_asset_type INTEGER,
        ///    serialized_size INTEGER,
        ///    streamed_size INTEGER,
        ///    PRIMARY KEY (id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildExplicitAssets {
            get {
                return ResourceManager.GetString("AddrBuildExplicitAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_file_assets
        ///(
        ///    file_id INTEGER,
        ///    build_id INTEGER,
        ///    asset_rid INTEGER,
        ///    PRIMARY KEY (file_id, build_id, asset_rid),
        ///    FOREIGN KEY (file_id, build_id) REFERENCES addr_build_files(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildFileAssets {
            get {
                return ResourceManager.GetString("AddrBuildFileAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_file_external_references
        ///(
        ///    file_id INTEGER,
        ///    build_id INTEGER,
        ///    external_reference_rid INTEGER,
        ///    PRIMARY KEY (file_id, build_id, external_reference_rid),
        ///    FOREIGN KEY (file_id, build_id) REFERENCES addr_build_files(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildFileExternalReferences {
            get {
                return ResourceManager.GetString("AddrBuildFileExternalReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_file_other_assets
        ///(
        ///    file_id INTEGER,
        ///    build_id INTEGER,
        ///    other_asset_rid INTEGER,
        ///    PRIMARY KEY (file_id, build_id, other_asset_rid),
        ///    FOREIGN KEY (file_id, build_id) REFERENCES addr_build_files(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildFileOtherAssets {
            get {
                return ResourceManager.GetString("AddrBuildFileOtherAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_files
        ///(
        ///    id INTEGER,
        ///    build_id INTEGER,
        ///    bundle INTEGER,
        ///    bundle_object_info_size INTEGER,
        ///    mono_script_count INTEGER,
        ///    mono_script_size INTEGER,
        ///    name TEXT,
        ///    preload_info_size INTEGER,
        ///    write_result_filename TEXT,
        ///    PRIMARY KEY (id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildFiles {
            get {
                return ResourceManager.GetString("AddrBuildFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_file_sub_files
        ///(
        ///    file_id INTEGER,
        ///    build_id INTEGER,
        ///    sub_file_rid INTEGER,
        ///    PRIMARY KEY (file_id, build_id, sub_file_rid),
        ///    FOREIGN KEY (file_id, build_id) REFERENCES addr_build_files(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildFileSubFiles {
            get {
                return ResourceManager.GetString("AddrBuildFileSubFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_group_bundles
        ///(
        ///    group_id INTEGER,
        ///    build_id INTEGER,
        ///    bundle_rid INTEGER,
        ///    PRIMARY KEY (group_id, build_id, bundle_rid),
        ///    FOREIGN KEY (group_id, build_id) REFERENCES addr_build_groups(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildGroupBundles {
            get {
                return ResourceManager.GetString("AddrBuildGroupBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_groups
        ///(
        ///    id INTEGER,
        ///    build_id INTEGER,
        ///    guid TEXT,
        ///    name TEXT,
        ///    packing_mode TEXT,
        ///    PRIMARY KEY (id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildGroups {
            get {
                return ResourceManager.GetString("AddrBuildGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_group_schemas
        ///(
        ///    group_id INTEGER,
        ///    build_id INTEGER,
        ///    schema_rid INTEGER,
        ///    PRIMARY KEY (group_id, build_id, schema_rid),
        ///    FOREIGN KEY (group_id, build_id) REFERENCES addr_build_groups(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildGroupSchemas {
            get {
                return ResourceManager.GetString("AddrBuildGroupSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE addr_builds
        ///(
        ///    id INTEGER,
        ///    name TEXT,
        ///    build_target INTEGER,
        ///    start_time TEXT,
        ///    duration REAL,
        ///    error TEXT,
        ///    package_version TEXT,
        ///    player_version TEXT,
        ///    build_script TEXT,
        ///    result_hash TEXT,
        ///    type INTEGER,
        ///    unity_version TEXT,
        ///    PRIMARY KEY (id)
        ///);.
        /// </summary>
        internal static string AddrBuilds {
            get {
                return ResourceManager.GetString("AddrBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_schema_data_pairs
        ///(
        ///    schema_id INTEGER,
        ///    build_id INTEGER,
        ///    key TEXT,
        ///    value TEXT,
        ///    PRIMARY KEY (schema_id, build_id, key),
        ///    FOREIGN KEY (schema_id, build_id) REFERENCES addr_build_schemas(id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildSchemaDataPairs {
            get {
                return ResourceManager.GetString("AddrBuildSchemaDataPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_schemas
        ///(
        ///    id INTEGER,
        ///    build_id INTEGER,
        ///    guid TEXT,
        ///    type TEXT,
        ///    PRIMARY KEY (id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildSchemas {
            get {
                return ResourceManager.GetString("AddrBuildSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table addr_build_sub_files
        ///(
        ///    id INTEGER,
        ///    build_id INTEGER,
        ///    is_serialized_file INTEGER,
        ///    name TEXT,
        ///    size INTEGER,
        ///    PRIMARY KEY (id, build_id)
        ///);.
        /// </summary>
        internal static string AddrBuildSubFiles {
            get {
                return ResourceManager.GetString("AddrBuildSubFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE animation_clips(
        ///    id INTEGER,
        ///    legacy INTEGER,
        ///    events INTEGER,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE VIEW animation_view AS
        ///SELECT
        ///    o.*,
        ///    a.legacy,
        ///    a.events
        ///FROM object_view o INNER JOIN animation_clips a ON o.id = a.id;
        ///.
        /// </summary>
        internal static string AnimationClip {
            get {
                return ResourceManager.GetString("AnimationClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE assets(
        ///    object INTEGER,
        ///    name TEXT
        ///);
        ///
        ///CREATE TABLE asset_dependencies(
        ///    object INTEGER,
        ///    dependency INTEGER
        ///);
        ///
        ///CREATE VIEW asset_view AS
        ///SELECT
        ///    a.name AS asset_name,
        ///    o.*
        ///FROM assets a INNER JOIN object_view o ON o.id = a.object;
        ///
        ///CREATE VIEW asset_dependencies_view AS
        ///SELECT a.id, a.asset_name, a.asset_bundle, a.type, od.id dep_id, od.asset_bundle dep_asset_bundle, od.name dep_name, od.type dep_type
        ///FROM asset_view a
        ///INNER JOIN asset_dependencies d ON a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssetBundle {
            get {
                return ResourceManager.GetString("AssetBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE audio_load_types(
        ///    id INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE audio_formats(
        ///    id INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE audio_clips(
        ///    id INTEGER,
        ///    bits_per_sample INTEGER,
        ///    frequency INTEGER,
        ///    channels INTEGER,
        ///    load_type INTEGER,
        ///    format INTEGER,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE VIEW audio_clip_view AS
        ///SELECT
        ///	o.*,
        ///	a.bits_per_sample,
        ///	a.frequency,
        ///	a.channels,
        ///	l.name AS load_type,
        ///	f.name AS form [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AudioClip {
            get {
                return ResourceManager.GetString("AudioClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX refs_object_index ON refs(object);
        ///CREATE INDEX refs_referenced_object_index ON refs(referenced_object);
        ///.
        /// </summary>
        internal static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE types
        ///(
        ///    id INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE asset_bundles
        ///(
        ///    id INTEGER,
        ///    name TEXT,
        ///    file_size INTEGER,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE serialized_files
        ///(
        ///    id INTEGER,
        ///    asset_bundle INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE objects
        ///(
        ///    id INTEGER,
        ///    object_id INTEGER,
        ///    serialized_file INTEGER,
        ///    type INTEGER,
        ///    name TEXT,
        ///    game_object INTEGER,
        ///    size INTEGER,
        ///    crc32 INTE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE meshes(
        ///    id INTEGER,
        ///    sub_meshes INTEGER,
        ///    blend_shapes INTEGER,
        ///    bones INTEGER,
        ///    indices INTEGER,
        ///    vertices INTEGER,
        ///    compression INTEGER,
        ///    rw_enabled INTEGER,
        ///    vertex_size INTEGER,
        ///    channels TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE VIEW mesh_view AS
        ///SELECT
        ///    o.*,
        ///    m.sub_meshes,
        ///    m.blend_shapes,
        ///    m.bones,
        ///    m.indices,
        ///    m.vertices,
        ///    m.compression,
        ///    m.rw_enabled,
        ///    m.vertex_size,
        ///    m.channels
        ///FROM meshes m
        ///INNER JOIN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mesh {
            get {
                return ResourceManager.GetString("Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE shaders(
        ///    id INTEGER,
        ///    decompressed_size INTEGER,
        ///    unique_programs INTEGER,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE shader_keywords(
        ///    id INTEGER,
        ///    keyword TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE shader_subprogram_keywords(
        ///    subprogram_id INTEGER,
        ///    keyword_id INTEGER
        ///);
        ///
        ///CREATE TABLE shader_apis(
        ///    id INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE shader_subprograms(
        ///    id INTEGER,
        ///    shader INTEGER,
        ///    sub_shader INTEGER,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shader {
            get {
                return ResourceManager.GetString("Shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE texture_formats
        ///(
        ///    id INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE textures
        ///(
        ///    id INTEGER,
        ///    width INTEGER,
        ///    height INTEGER,
        ///    format INTEGER,
        ///    mip_count INTEGER,
        ///    rw_enabled INTEGER,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE VIEW texture_view AS
        ///SELECT
        ///    o.*,
        ///    t.width,
        ///    t.height,
        ///    f.name AS format,
        ///    t.mip_count,
        ///    t.rw_enabled
        ///FROM object_view o
        ///INNER JOIN textures t ON o.id = t.id
        ///LEFT JOIN texture_formats f ON t.format = f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Texture2D {
            get {
                return ResourceManager.GetString("Texture2D", resourceCulture);
            }
        }
    }
}
