//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityDataTools.Analyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE animation_clips(
        ///    id INTEGER,
        ///    legacy INTEGER,
        ///    events INTEGER,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE VIEW animation_view AS
        ///SELECT
        ///    o.*,
        ///    a.legacy,
        ///    a.events
        ///FROM object_view o INNER JOIN animation_clips a ON o.id = a.id;
        ///.
        /// </summary>
        internal static string AnimationClip {
            get {
                return ResourceManager.GetString("AnimationClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE assets(
        ///    object INTEGER,
        ///    name TEXT
        ///);
        ///
        ///CREATE VIEW asset_view AS
        ///SELECT
        ///    a.name AS asset_name,
        ///    o.*
        ///FROM assets a INNER JOIN object_view o ON o.id = a.object;
        ///.
        /// </summary>
        internal static string AssetBundle {
            get {
                return ResourceManager.GetString("AssetBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE audio_load_types(
        ///    id INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE audio_formats(
        ///    id INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE audio_clips(
        ///    id INTEGER,
        ///    bits_per_sample INTEGER,
        ///    frequency INTEGER,
        ///    channels INTEGER,
        ///    load_type INTEGER,
        ///    format INTEGER,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE VIEW audio_clip_view AS
        ///SELECT
        ///	o.*,
        ///	a.bits_per_sample,
        ///	a.frequency,
        ///	a.channels,
        ///	l.name AS load_type,
        ///	f.name AS form [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AudioClip {
            get {
                return ResourceManager.GetString("AudioClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX refs_object_index ON refs(object);
        ///CREATE INDEX refs_referenced_object_index ON refs(referenced_object);
        ///.
        /// </summary>
        internal static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE types
        ///(
        ///    id INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE asset_bundles
        ///(
        ///    id INTEGER,
        ///    name TEXT,
        ///    file_size INTEGER,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE serialized_files
        ///(
        ///    id INTEGER,
        ///    asset_bundle INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE objects
        ///(
        ///    id INTEGER,
        ///    object_id INTEGER,
        ///    serialized_file INTEGER,
        ///    type INTEGER,
        ///    name TEXT,
        ///    game_object INTEGER,
        ///    size INTEGER,
        ///    PRIMARY KE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE meshes(
        ///    id INTEGER,
        ///    sub_meshes INTEGER,
        ///    blend_shapes INTEGER,
        ///    bones INTEGER,
        ///    indices INTEGER,
        ///    vertices INTEGER,
        ///    compression INTEGER,
        ///    rw_enabled INTEGER,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE VIEW mesh_view AS
        ///SELECT
        ///    o.*,
        ///    m.sub_meshes,
        ///    m.blend_shapes,
        ///    m.bones,
        ///    m.indices,
        ///    m.vertices,
        ///    m.compression,
        ///    m.rw_enabled
        ///FROM meshes m
        ///INNER JOIN object_view o ON o.id = m.id;
        ///.
        /// </summary>
        internal static string Mesh {
            get {
                return ResourceManager.GetString("Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE shaders(
        ///    id INTEGER,
        ///    decompressed_size INTEGER,
        ///    sub_shaders INTEGER,
        ///    unique_programs INTEGER,
        ///    keywords TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE shader_apis(
        ///    id INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE shader_subprograms(
        ///    shader INTEGER,
        ///    pass INTEGER,
        ///    sub_program INTEGER,
        ///    hw_tier INTEGER,
        ///    shader_type TEXT,
        ///    api INTEGER,
        ///    keywords TEXT
        ///);
        ///
        ///CREATE VIEW shader_view AS
        ///SELECT
        ///    o.*,
        ///    s.decompre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shader {
            get {
                return ResourceManager.GetString("Shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE texture_formats
        ///(
        ///    id INTEGER,
        ///    name TEXT,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE TABLE textures
        ///(
        ///    id INTEGER,
        ///    width INTEGER,
        ///    height INTEGER,
        ///    format INTEGER,
        ///    mip_count INTEGER,
        ///    rw_enabled INTEGER,
        ///    PRIMARY KEY (id)
        ///);
        ///
        ///CREATE VIEW texture_view AS
        ///SELECT
        ///    o.*,
        ///    t.width,
        ///    t.height,
        ///    f.name AS format,
        ///    t.mip_count,
        ///    t.rw_enabled
        ///FROM object_view o
        ///INNER JOIN textures t ON o.id = t.id
        ///LEFT JOIN texture_formats f ON t.format = f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Texture2D {
            get {
                return ResourceManager.GetString("Texture2D", resourceCulture);
            }
        }
    }
}
