using System;
using Microsoft.Data.Sqlite;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;

namespace UnityDataTools.UnityDataTool.Tests;

#pragma warning disable NUnit2005, NUnit2006

public class BuildReportTests
{
    private string m_TestOutputFolder;
    private string m_TestDataFolder;

    [OneTimeSetUp]
    public void OneTimeSetup()
    {
        m_TestOutputFolder = Path.Combine(TestContext.CurrentContext.TestDirectory, "test_folder");
        m_TestDataFolder = Path.Combine(TestContext.CurrentContext.TestDirectory, "Data");
        Directory.CreateDirectory(m_TestOutputFolder);
        Directory.SetCurrentDirectory(m_TestOutputFolder);
    }

    [TearDown]
    public void Teardown()
    {
        SqliteConnection.ClearAllPools();

        var testDir = new DirectoryInfo(m_TestOutputFolder);
        testDir.EnumerateFiles()
            .ToList().ForEach(f => f.Delete());
        testDir.EnumerateDirectories()
            .ToList().ForEach(d => d.Delete(true));
    }

    [Test]
    public async Task Analyze_BuildReport_ContainsExpectedSQLContent()
    {
        // This folder contains a reference build report generated by a build of the TestProject
        // in the BuildReportInspector package.
        var path = Path.Combine(m_TestDataFolder, "BuildReport1");
        var databasePath = Path.Combine(m_TestOutputFolder, "database.db");

        Assert.AreEqual(0, await Program.Main(new string[] { "analyze", path, "-p", "*.buildreport" }));
        using var db = new SqliteConnection(new SqliteConnectionStringBuilder
        {
            DataSource = databasePath,
            Mode = SqliteOpenMode.ReadWriteCreate,
            Pooling = false,
            ForeignKeys = false,
        }.ConnectionString);
        db.Open();

        using var cmd = db.CreateCommand();

        // Sanity check the Unity objects found in this Build report file
        // Tip: The names for the hardcoded type ids in the query can be found
        // at https://docs.unity3d.com/6000.3/Documentation/Manual/ClassIDReference.html

        // The BuildReport object is the most important.
        // And PackedAssets objects are present for each output serialized file, .resS and .resource.
        // Other obscure objects can also be present like PluginBuildInfo,
        // and BuiltAssetBundleInfoSet (these are internal, and subject to change)
        cmd.CommandText =
            @"SELECT
                (SELECT COUNT(*) FROM objects),
                (SELECT COUNT(*) FROM objects WHERE type = 1125),
                (SELECT COUNT(*) FROM objects WHERE type = 1126),
                (SELECT COUNT(*) FROM objects WHERE type = 382020655),
                (SELECT COUNT(*) FROM objects WHERE type = 668709126),
                (SELECT COUNT(*) FROM objects WHERE type = 641289076),
                (SELECT COUNT(*) FROM objects WHERE type = 1521398425),
                (SELECT COUNT(*) FROM asset_bundles)";

        using var reader = cmd.ExecuteReader();
        reader.Read();

        Assert.AreEqual(12, reader.GetInt32(0), "Unexpected number of objects");
        Assert.AreEqual(1, reader.GetInt32(1), "Unexpected number of BuildReport objects (type 1125)");
        Assert.AreEqual(7, reader.GetInt32(2), "Unexpected number of PackedAssets objects");
        Assert.AreEqual(1, reader.GetInt32(3), "Unexpected number of PluginBuildInfo objects");
        Assert.AreEqual(1, reader.GetInt32(4), "Unexpected number of BuiltAssetBundleInfoSet objects");
        Assert.AreEqual(1, reader.GetInt32(5), "Unexpected number of AudioBuildInfo objects");
        Assert.AreEqual(1, reader.GetInt32(6), "Unexpected number of VideoBuildInfo objects");
        Assert.AreEqual(0, reader.GetInt32(7), "Expected no AssetBundles found in reference folder");
    }
}
