using System;
using Microsoft.Data.Sqlite;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;

namespace UnityDataTools.UnityDataTool.Tests;

#pragma warning disable NUnit2005, NUnit2006

public class BuildReportTests
{
    private string m_TestOutputFolder;
    private string m_TestDataFolder;

    [OneTimeSetUp]
    public void OneTimeSetup()
    {
        m_TestOutputFolder = Path.Combine(TestContext.CurrentContext.TestDirectory, "test_folder");
        m_TestDataFolder = Path.Combine(TestContext.CurrentContext.TestDirectory, "Data");
        Directory.CreateDirectory(m_TestOutputFolder);
        Directory.SetCurrentDirectory(m_TestOutputFolder);
    }

    [TearDown]
    public void Teardown()
    {
        SqliteConnection.ClearAllPools();

        var testDir = new DirectoryInfo(m_TestOutputFolder);
        testDir.EnumerateFiles()
            .ToList().ForEach(f => f.Delete());
        testDir.EnumerateDirectories()
            .ToList().ForEach(d => d.Delete(true));
    }

    [Test]
    public async Task Analyze_BuildReport_ContainsExpectedSQLContent()
    {
        // This folder contains a reference build report generated by a build of the TestProject
        // in the BuildReportInspector package.
        var path = Path.Combine(m_TestDataFolder, "BuildReport1");
        var databasePath = Path.Combine(m_TestOutputFolder, "database.db");

        Assert.AreEqual(0, await Program.Main(new string[] { "analyze", path, "-p", "*.buildreport" }));
        using var db = new SqliteConnection(new SqliteConnectionStringBuilder
        {
            DataSource = databasePath,
            Mode = SqliteOpenMode.ReadWriteCreate,
            Pooling = false,
            ForeignKeys = false,
        }.ConnectionString);
        db.Open();

        // Sanity check the Unity objects found in this Build report file
        // Tip: The names for the hardcoded type ids in the query can be found
        // at https://docs.unity3d.com/6000.3/Documentation/Manual/ClassIDReference.html

        // The BuildReport object is the most important.
        // And PackedAssets objects are present for each output serialized file, .resS and .resource.
        // Other obscure objects can also be present like PluginBuildInfo,
        // and BuiltAssetBundleInfoSet (these are internal, and subject to change)

        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM objects", 12,
            "Unexpected number of objects");
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM objects WHERE type = 1125", 1,
            "Unexpected number of BuildReport objects (type 1125)");
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM objects WHERE type = 1126", 7,
            "Unexpected number of PackedAssets objects");
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM objects WHERE type = 382020655", 1,
            "Unexpected number of PluginBuildInfo objects");
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM objects WHERE type = 668709126", 1,
            "Unexpected number of BuiltAssetBundleInfoSet objects");
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM objects WHERE type = 641289076", 1,
            "Unexpected number of AudioBuildInfo objects");
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM objects WHERE type = 1521398425", 1,
            "Unexpected number of VideoBuildInfo objects");
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM asset_bundles", 0,
            "Expected no AssetBundles found in reference folder");

        // Can check name on BuildReport object ("Build AssetBundles")
        // Use object_view to avoid the hardcoded ids.
        // Can test references (BuildReport m_Appendices[] fields)
        // Can also check view_breakdown_by_type as sanity check
    }
}
