using Microsoft.Data.Sqlite;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;
using System.Collections.Generic;

namespace UnityDataTools.UnityDataTool.Tests;

#pragma warning disable NUnit2005, NUnit2006

public class BuildReportTests
{
    private string m_TestOutputFolder;
    private string m_TestDataFolder;

    [OneTimeSetUp]
    public void OneTimeSetup()
    {
        m_TestOutputFolder = Path.Combine(TestContext.CurrentContext.TestDirectory, "test_folder");
        m_TestDataFolder = Path.Combine(TestContext.CurrentContext.TestDirectory, "Data");
        Directory.CreateDirectory(m_TestOutputFolder);
        Directory.SetCurrentDirectory(m_TestOutputFolder);
    }

    [TearDown]
    public void Teardown()
    {
        SqliteConnection.ClearAllPools();

        var testDir = new DirectoryInfo(m_TestOutputFolder);
        testDir.EnumerateFiles()
            .ToList().ForEach(f => f.Delete());
        testDir.EnumerateDirectories()
            .ToList().ForEach(d => d.Delete(true));
    }

    // Check the primary object/file tables and views which are populated by the general
    // object handling of the analyzer (e.g. nothing BuildReport specific)
    // This test is parameterized to run with and without "--skip-references"
    // in order to show that the core object tables are not impacted by whether
    // or not references are tracked.
    [Test]
    public async Task Analyze_BuildReport_ContainsExpected_ObjectInfo(
        [Values(false, true)] bool skipReferences)
    {
        // This folder contains a reference build report generated by a build of the TestProject
        // in the BuildReportInspector package.
        var path = Path.Combine(m_TestDataFolder, "BuildReport1");
        var databasePath = SQLTestHelper.GetDatabasePath(m_TestOutputFolder);

        var args = new List<string> { "analyze", path, "-p", "*.buildreport" };
        if (skipReferences)
            args.Add("--skip-references");

        Assert.AreEqual(0, await Program.Main(args.ToArray()));
        using var db = SQLTestHelper.OpenDatabase(databasePath);

        // Sanity check the Unity objects found in this Build report file
        // Tip: The meaning of the hard coded type ids used in the queries can be found
        // at https://docs.unity3d.com/6000.3/Documentation/Manual/ClassIDReference.html

        // The BuildReport object is the most important.
        // PackedAssets objects are present for each output serialized file, .resS and .resource.
        const int packedAssetCount = 7;

        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM objects WHERE type = 1125", 1,
            "Unexpected number of BuildReport objects (type 1125)");
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM objects WHERE type = 1126", packedAssetCount,
            "Unexpected number of PackedAssets objects");

        // This object is expected inside AssetBundle builds
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM objects WHERE type = 668709126", 1,
            "Unexpected number of BuiltAssetBundleInfoSet objects");

        // There can be other more obscure objects present, depending on the build,
        // e.g. PluginBuildInfo, AudioBuildInfo, VideoBuildInfo etc.
        var ttlObjCount = SQLTestHelper.QueryInt(db, "SELECT COUNT(*) FROM objects");
        Assert.That(ttlObjCount, Is.GreaterThanOrEqualTo(1+ packedAssetCount + 1),
            "Unexpected number of objects in BuildReport analysis");

        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM asset_bundles", 0,
            "Expected no AssetBundles found in reference folder");

        //
        // Tests using object_view which lets us refer to objects by type name
        //
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM object_view WHERE type = 'BuildReport'", 1,
            "Expected exactly one BuildReport in object_view");

        SQLTestHelper.AssertQueryString(db, "SELECT name FROM object_view WHERE type = 'BuildReport'", "Build AssetBundles",
            "Unexpected name");

        SQLTestHelper.AssertQueryString(db, "SELECT name FROM object_view WHERE type = 'BuildReport'", "Build AssetBundles",
            "Unexpected BuildReport name in object_view");

        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM object_view WHERE type = 'PackedAssets'", packedAssetCount,
            "Unexpected number of PackedAssets in object_view");

        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM object_view WHERE type = 'BuiltAssetBundleInfoSet'", 1,
            "Expected exactly one BuiltAssetBundleInfoSet in object_view");

        // Verify all rows have the same serialized_file
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(DISTINCT serialized_file) FROM object_view", 1,
            "All objects should be from the same serialized file");

        SQLTestHelper.AssertQueryString(db, "SELECT DISTINCT serialized_file FROM object_view", "LastBuild.buildreport",
            "Unexpected serialized file name in object_view");

        // Verify the BuildReport object has expected properties
        var buildReportSize = SQLTestHelper.QueryInt(db, "SELECT size FROM object_view WHERE type = 'BuildReport'");
        Assert.That(buildReportSize, Is.GreaterThan(0), "BuildReport size should be greater than 0");

        //
        // Tests using view_breakdown_by_type which aggregates objects by type
        //

        // Verify counts match for specific types
        SQLTestHelper.AssertQueryInt(db, "SELECT count FROM view_breakdown_by_type WHERE type = 'BuildReport'", 1,
            "Expected 1 BuildReport in breakdown view");
        SQLTestHelper.AssertQueryInt(db, "SELECT count FROM view_breakdown_by_type WHERE type = 'PackedAssets'", packedAssetCount,
            "Expected 7 PackedAssets in breakdown view");

        var buildReportSize2 = SQLTestHelper.QueryInt(db, "SELECT byte_size FROM view_breakdown_by_type WHERE type = 'BuildReport'");
        Assert.AreEqual(buildReportSize, buildReportSize2, "Mismatch between object_view and breakdown_view for BuildReport size");

        // Verify pretty_size formatting exists
        var buildReportPrettySize = SQLTestHelper.QueryString(db, "SELECT pretty_size FROM view_breakdown_by_type WHERE type = 'BuildReport'");
        Assert.That(buildReportPrettySize, Does.Contain("KB").Or.Contain("B"), "BuildReport pretty_size should have size unit");

        // Verify total byte_size across all types
        var totalSize = SQLTestHelper.QueryInt(db, "SELECT SUM(byte_size) FROM view_breakdown_by_type");
        Assert.That(totalSize, Is.GreaterThan(buildReportSize),
            "Unexpected number of objects in BuildReport analysis");

        //
        // Tests using serialized_files table
        //
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM serialized_files", 1,
            "Expected exactly one serialized file");

        SQLTestHelper.AssertQueryString(db, "SELECT name FROM serialized_files WHERE id = 0", "LastBuild.buildreport",
            "Unexpected serialized file name");

        // Verify asset_bundle column is empty/NULL for BuildReport files (they are not asset bundles)
        var assetBundleValue = SQLTestHelper.QueryString(db, "SELECT COALESCE(asset_bundle, '') FROM serialized_files WHERE id = 0");
        Assert.That(string.IsNullOrEmpty(assetBundleValue), "BuildReport serialized file should not have asset_bundle value");

        // Verify the serialized file name matches what we see in object_view
        var serializedFileName = SQLTestHelper.QueryString(db, "SELECT name FROM serialized_files WHERE id = 0");
        var objectViewFileName = SQLTestHelper.QueryString(db, "SELECT DISTINCT serialized_file FROM object_view");
        Assert.AreEqual(serializedFileName, objectViewFileName,
            "Serialized file name should match between serialized_files table and object_view");
    }

    // The BuildReport file has a simple structure with a single BuildReport object
    // and all other objects referenced from its Appendicies array.
    // This gives an opportunity for a detailed test that the "refs" table is properly populated.
    [Test]
    public async Task Analyze_BuildReport_ContainsExpectedReferences(
        [Values(false, true)] bool skipReferences)
    {
        var path = Path.Combine(m_TestDataFolder, "BuildReport1");
        var databasePath = SQLTestHelper.GetDatabasePath(m_TestOutputFolder);

        var args = new List<string> { "analyze", path, "-p", "*.buildreport" };
        if (skipReferences)
            args.Add("--skip-references");

        Assert.AreEqual(0, await Program.Main(args.ToArray()));
        using var db = SQLTestHelper.OpenDatabase(databasePath);

        if (skipReferences)
        {
            // When --skip-references is used, the refs table should be empty
            SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM refs", 0,
                "refs table should be empty when --skip-references is used");
            return;
        }

        var buildReportId = SQLTestHelper.QueryInt(db,
            "SELECT id FROM objects WHERE type = 1125");

        var totalObjectCount = SQLTestHelper.QueryInt(db, "SELECT COUNT(*) FROM objects");

        var expectedRefCount = totalObjectCount - 1;
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM refs", expectedRefCount,
            "BuildReport should reference all other objects");

        SQLTestHelper.AssertQueryInt(db, $"SELECT COUNT(*) FROM refs WHERE object = {buildReportId}", expectedRefCount,
            "All references should originate from BuildReport object");

        SQLTestHelper.AssertQueryInt(db, $"SELECT COUNT(*) FROM refs WHERE referenced_object = {buildReportId}", 0,
            "No object should reference the BuildReport object");

        var refsWithWrongPath = SQLTestHelper.QueryInt(db,
            "SELECT COUNT(*) FROM refs WHERE property_path NOT LIKE 'm_Appendices[%]'");
        Assert.AreEqual(0, refsWithWrongPath, "All property_path values should match pattern 'm_Appendices[N]'");

        SQLTestHelper.AssertQueryString(db, "SELECT DISTINCT property_type FROM refs", "Object",
            "All references should have property_type 'Object'");

        var objectsNotReferenced = SQLTestHelper.QueryInt(db,
            $@"SELECT COUNT(*) FROM objects
                WHERE id != {buildReportId}
                AND id NOT IN (SELECT referenced_object FROM refs)");
        Assert.AreEqual(0, objectsNotReferenced,
            "Every object except BuildReport should be referenced exactly once");

        var duplicateRefs = SQLTestHelper.QueryInt(db,
            "SELECT COUNT(*) FROM (SELECT referenced_object, COUNT(*) as cnt FROM refs GROUP BY referenced_object HAVING cnt > 1)");
        Assert.AreEqual(0, duplicateRefs,
            "No object should be referenced more than once");
    }

    // Test the BuildReport-specific table and view
    [Test]
    public async Task Analyze_BuildReport_ContainsBuildReportData()
    {
        var path = Path.Combine(m_TestDataFolder, "BuildReport1");
        var databasePath = SQLTestHelper.GetDatabasePath(m_TestOutputFolder);

        var args = new List<string> { "analyze", path, "-p", "*.buildreport" };

        Assert.AreEqual(0, await Program.Main(args.ToArray()));
        using var db = SQLTestHelper.OpenDatabase(databasePath);

        // Verify build_reports table has one row
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM build_reports", 1,
            "Expected exactly one row in build_reports table");

        // Verify build_report_view has one row
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM build_report_view", 1,
            "Expected exactly one row in build_report_view");

        // Verify specific fields from m_Summary
        SQLTestHelper.AssertQueryString(db, "SELECT platform_name FROM build_report_view", "Win64",
            "Unexpected platform_name");

        SQLTestHelper.AssertQueryString(db, "SELECT build_type FROM build_report_view", "AssetBundle",
            "Unexpected build_type - should be 'AssetBundle' not the numeric value");

        SQLTestHelper.AssertQueryInt(db, "SELECT subtarget FROM build_report_view", 2,
            "Unexpected subtarget");

        SQLTestHelper.AssertQueryInt(db, "SELECT total_errors FROM build_report_view", 0,
            "Unexpected total_errors");

        SQLTestHelper.AssertQueryInt(db, "SELECT total_warnings FROM build_report_view", 0,
            "Unexpected total_warnings");

        SQLTestHelper.AssertQueryInt(db, "SELECT build_result FROM build_report_view", 1,
            "Unexpected build_result");

        // Verify output_path is present
        var outputPath = SQLTestHelper.QueryString(db, "SELECT output_path FROM build_report_view");
        Assert.That(outputPath, Does.Contain("AssetBundles"), "Output path should contain 'AssetBundles'");

        // Verify total_size is greater than 0
        var totalSize = SQLTestHelper.QueryInt(db, "SELECT total_size FROM build_report_view");
        Assert.That(totalSize, Is.GreaterThan(0), "total_size should be greater than 0");

        // Verify the view joins correctly with object_view data
        SQLTestHelper.AssertQueryString(db, "SELECT name FROM build_report_view", "Build AssetBundles",
            "name from object_view should be accessible in build_report_view");

        SQLTestHelper.AssertQueryString(db, "SELECT type FROM build_report_view", "BuildReport",
            "type from object_view should be accessible in build_report_view");
    }

    // Test the BuildReport-specific table with a Player build (not AssetBundle build)
    [Test]
    public async Task Analyze_BuildReport_Player_ContainsBuildReportData()
    {
        var path = Path.Combine(m_TestDataFolder, "BuildReport-Player");
        var databasePath = SQLTestHelper.GetDatabasePath(m_TestOutputFolder);

        var args = new List<string> { "analyze", path, "-p", "*.buildreport" };

        Assert.AreEqual(0, await Program.Main(args.ToArray()));
        using var db = SQLTestHelper.OpenDatabase(databasePath);

        // Verify build_reports table has one row
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM build_reports", 1,
            "Expected exactly one row in build_reports table");

        // Verify build_report_view has one row
        SQLTestHelper.AssertQueryInt(db, "SELECT COUNT(*) FROM build_report_view", 1,
            "Expected exactly one row in build_report_view");

        // Verify build_type is "Player" not "AssetBundle"
        SQLTestHelper.AssertQueryString(db, "SELECT build_type FROM build_report_view", "Player",
            "Unexpected build_type - should be 'Player' for player builds");

        // Verify buildGUID was correctly parsed
        // Expected: data[0]=3856716653, data[1]=3821322382, data[2]=1211319241, data[3]=2950543120
        // Unity's GUID format reverses nibbles within each uint32 (see GUIDToString in Unity C++)
        SQLTestHelper.AssertQueryString(db, "SELECT build_guid FROM build_report_view", "d63d0e5ee80c4c3e9c343384017bddfa",
            "Unexpected build_guid");

        // Verify subtarget
        SQLTestHelper.AssertQueryInt(db, "SELECT subtarget FROM build_report_view", 2,
            "Unexpected subtarget");

        // Verify options (should be 9 for this Player build)
        SQLTestHelper.AssertQueryInt(db, "SELECT options FROM build_report_view", 9,
            "Unexpected options value");

        // Verify build_result (1 = Success)
        SQLTestHelper.AssertQueryInt(db, "SELECT build_result FROM build_report_view", 1,
            "Unexpected build_result");

        // Verify name
        SQLTestHelper.AssertQueryString(db, "SELECT name FROM build_report_view", "New Report",
            "Unexpected BuildReport name");

        // Verify total_size is greater than 0
        var totalSize = SQLTestHelper.QueryInt(db, "SELECT total_size FROM build_report_view");
        Assert.That(totalSize, Is.GreaterThan(0), "total_size should be greater than 0");

        // Verify output_path contains expected path
        var outputPath = SQLTestHelper.QueryString(db, "SELECT output_path FROM build_report_view");
        Assert.That(outputPath, Does.Contain("TestProject.exe"), "Output path should contain 'TestProject.exe' for player build");
    }
}
