using System.Collections.Generic;

namespace UnityDataTools.FileSystem;

/// <summary>
/// Registry of common Unity TypeIds mapped to their type names.
/// Used as a fallback when TypeTree information is not available.
/// Reference: https://docs.unity3d.com/Manual/ClassIDReference.html
/// </summary>
public static class TypeIdRegistry
{
    private static readonly Dictionary<int, string> s_KnownTypes = new()
    {
        { 1, "GameObject" },
        { 2, "Component" },
        { 4, "Transform" },
        { 8, "Behaviour" },
        { 18, "EditorExtension" },
        { 19, "Physics2DSettings" },
        { 20, "Camera" },
        { 21, "Material" },
        { 23, "MeshRenderer" },
        { 25, "Renderer" },
        { 27, "Texture" },
        { 28, "Texture2D" },
        { 33, "MeshFilter" },
        { 41, "OcclusionPortal" },
        { 43, "Mesh" },
        { 45, "Skybox" },
        { 47, "QualitySettings" },
        { 48, "Shader" },
        { 49, "TextAsset" },
        { 50, "Rigidbody2D" },
        { 54, "Rigidbody" },
        { 55, "PhysicsManager" },
        { 56, "Collider" },
        { 58, "CircleCollider2D" },
        { 59, "PolygonCollider2D" },
        { 60, "BoxCollider2D" },
        { 61, "PhysicsMaterial2D" },
        { 62, "MeshCollider" },
        { 64, "BoxCollider" },
        { 65, "SphereCollider" },
        { 68, "EdgeCollider2D" },
        { 72, "ComputeShader" },
        { 74, "AnimationClip" },
        { 78, "TagManager" },
        { 81, "AudioListener" },
        { 82, "AudioSource" },
        { 83, "AudioClip" },
        { 84, "RenderTexture" },
        { 89, "Cubemap" },
        { 90, "Avatar" },
        { 91, "AnimatorController" },
        { 93, "RuntimeAnimatorController" },
        { 95, "Animator" },
        { 96, "TrailRenderer" },
        { 102, "TextMesh" },
        { 104, "RenderSettings" },
        { 108, "Light" },
        { 109, "ShaderInclude" },
        { 114, "MonoBehaviour" },
        { 115, "MonoScript" },
        { 117, "Texture3D" },
        { 120, "LineRenderer" },
        { 121, "ReflectionProbe" },
        { 128, "Font" },
        { 129, "PlayerSettings" },
        { 134, "PhysicsMaterial" },
        { 135, "SphereCollider" },
        { 136, "CapsuleCollider" },
        { 137, "SkinnedMeshRenderer" },
        { 142, "AssetBundle" },
        { 143, "CharacterController" },
        { 144, "CharacterJoint" },
        { 145, "SpringJoint" },
        { 146, "WheelCollider" },
        { 147, "ResourceManager" },
        { 150, "PreloadData" },
        { 153, "ConfigurableJoint" },
        { 154, "TerrainCollider" },
        { 156, "TerrainData" },
        { 157, "LightmapSettings" },
        { 158, "WebCamTexture" },
        { 184, "SubstanceArchive" },
        { 185, "ProceduralMaterial" },
        { 186, "ProceduralTexture" },
        { 187, "Texture2DArray" },
        { 188, "CubemapArray" },
        { 191, "OffMeshLink" },
        { 192, "OcclusionArea" },
        { 193, "Tree" },
        { 194, "NavMeshAgent" },
        { 195, "NavMeshSettings" },
        { 196, "NavMeshObstacle" },
        { 198, "ParticleSystem" },
        { 199, "ParticleSystemRenderer" },
        { 200, "ShaderVariantCollection" },
        { 205, "LODGroup" },
        { 206, "BlendTree" },
        { 207, "Motion" },
        { 208, "NavMeshData" },
        { 210, "SortingGroup" },
        { 212, "SpriteRenderer" },
        { 213, "Sprite" },
        { 215, "ReflectionProbe" },
        { 218, "Terrain" },
        { 220, "LightProbeGroup" },
        { 221, "AnimatorOverrideController" },
        { 222, "CanvasRenderer" },
        { 223, "Canvas" },
        { 224, "RectTransform" },
        { 225, "CanvasGroup" },
        { 226, "BillboardAsset" },
        { 227, "BillboardRenderer" },
        { 228, "SpeedTreeWindAsset" },
        { 229, "AnchoredJoint2D" },
        { 230, "Joint2D" },
        { 231, "SpringJoint2D" },
        { 232, "DistanceJoint2D" },
        { 233, "HingeJoint2D" },
        { 234, "SliderJoint2D" },
        { 235, "WheelJoint2D" },
        { 238, "NavMeshObstacle" },
        { 240, "OcclusionPortal" },
        { 241, "AudioMixer" },
        { 243, "AudioMixerController" },
        { 244, "AudioMixerGroupController" },
        { 245, "AudioMixerEffectController" },
        { 258, "AudioMixerSnapshotController" },
        { 259, "AudioMixerSnapshot" },
        { 290, "AssetBundleManifest" },
        { 1020, "DefaultAsset" },
        { 1028, "AnimatorStateTransition" },
        { 1029, "AnimatorState" },
        { 1030, "HumanTemplate" },
        { 1032, "SceneAsset" },
        { 1041, "HierarchyState" },
        { 1045, "AssetMetaData" },
        { 1101, "AnimatorTransition" },
        { 1102, "AnimatorTransitionBase" },
        { 1105, "AnimatorStateMachine" },
        { 1107, "AnimatorLayer" },
        { 1113, "Prefab" },
        { 1120, "LightmapParameters" },
        { 1125, "BuildReport" },
        { 1126, "PackedAssets" },
    };

    /// <param name="typeId">The Unity TypeId</param>
    /// <returns>The type name or TypeId as string if unknown</returns>
    public static string GetTypeName(int typeId)
    {
        return s_KnownTypes.TryGetValue(typeId, out var name)
            ? name
            : typeId.ToString();
    }
}

